<?php
# This file was automatically generated by the MediaWiki 1.43.1
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/MainConfigSchema.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# https://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if (!defined('MEDIAWIKI')) {
	exit;
}

## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename = "ADND2e";
$wgMetaNamespace = "AD&D2e";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs
## (like /w/index.php/Page_title to /wiki/Page_title) please see:
## https://www.mediawiki.org/wiki/Manual:Short_URL
// Base path settings
$wgScriptPath = "";
$wgArticlePath = "/wiki/$1"; // Enable pretty URLs

## The protocol and server name to use in fully-qualified URLs
$wgServer = "https://adnd2e.mayorgergich.xyz";

## The URL path to static resources (images, scripts, etc.)
$wgResourceBasePath = $wgScriptPath;

## The URL paths to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
$wgLogos = [
	'1x' => "$wgResourceBasePath/images/logo.png",
	'icon' => "$wgResourceBasePath/images/favicon.ico",
];

## UPO means: this is also a user preference option

$wgEnableEmail = true;
$wgEnableUserEmail = true; # UPO

$wgEmergencyContact = "";
$wgPasswordSender = "";

$wgEnotifUserTalk = false; # UPO
$wgEnotifWatchlist = false; # UPO
$wgEmailAuthentication = true;

## === DATABASE SETTINGS - ROBUST CONFIGURATION ===
## Database settings
$wgDBtype = "mysql";
$wgDBserver = "mariadb"; // Use hostname for container networking
$wgDBname = "adnd2e_db";
$wgDBuser = "pawneemayor";
$wgDBpassword = "password321";

# Database connection parameters - Adjusted for robustness
$wgDBconnectionAttempts = 3;  // Try more times
$wgDBretryAttempts = 3;       // Retry more times
$wgDBmwschemaRetryAttempts = 3;

# Use explicit database servers configuration for more control
$wgDBservers = [
    [
        'host' => 'mariadb',
        'dbname' => 'adnd2e_db',
        'user' => 'pawneemayor',
        'password' => 'password321',
        'type' => 'mysql',
        'flags' => DBO_DEFAULT,
        'load' => 1,
        'driver' => 'mysqli',
        'initCommands' => [],
        'conn_flags' => null, // Let the driver handle it
        'dns_cache_timeout' => 0, // Disable DNS caching
    ],
];

# MySQL specific settings
$wgDBprefix = ""; # Added prefix for separation
$wgDBssl = false;
$wgDBmysql5 = false; # Optimal for MariaDB 10+

# MySQL table options to use during installation or update
$wgDBTableOptions = "ENGINE=InnoDB, DEFAULT CHARSET=binary";

# Shared database table
# This has no effect unless $wgSharedDB is also set.
$wgSharedTables[] = "actor";

## === CACHING AND PERFORMANCE OPTIMIZATIONS ===
# Object caching - improves overall performance
$wgMainCacheType = CACHE_ACCEL;
$wgParserCacheType = CACHE_ACCEL;
$wgMessageCacheType = CACHE_ACCEL;
$wgMemCachedServers = [];

# File caching - great for reference material
$wgUseFileCache = true;
$wgFileCacheDirectory = "$IP/cache";
$wgCachePages = true;
$wgShowIPinHeader = false;

# Parser optimizations - reduces CPU usage
$wgEnableSidebarCache = true;
$wgAdaptiveMessageCache = true;

# Resource loader optimizations - faster page loads
$wgResourceLoaderMaxage['versioned'] = 60 * 60 * 24 * 30; // 30 days
$wgResourceLoaderMaxage['unversioned'] = 60 * 60 * 24; // 1 day

# Use compression for better performance
$wgUseGzip = true;

# Reduce background tasks for better reading performance
$wgJobRunRate = 0.01; // Minimal background jobs

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads = true;
$wgUseImageMagick = true;
$wgImageMagickConvertCommand = "/usr/bin/convert";

# InstantCommons allows wiki to use images from https://commons.wikimedia.org
$wgUseInstantCommons = false;

# Periodically send a pingback to https://www.mediawiki.org/ with basic data
# about this MediaWiki instance. The Wikimedia Foundation shares this data
# with MediaWiki developers to help guide future development efforts.
$wgPingback = true;

# Site language code, should be one of the list in ./includes/languages/data/Names.php
$wgLanguageCode = "en";

# Time zone
$wgLocaltimezone = "UTC";

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publicly accessible from the web.
$wgCacheDirectory = "$IP/cache";

# Ensure directory permissions are correct
$wgDirectoryMode = 0775;

$wgSecretKey = "2bb341eaf6836414e801e978a37eb6db4ec92b531fec7d7758ee27fe15424f6e";

# Changing this will log out all existing sessions.
$wgAuthenticationTokenVersion = "1";

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
$wgUpgradeKey = "65ad112463df7681";

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "";
$wgRightsText = "";
$wgRightsIcon = "";

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "/usr/bin/diff3";

## === SKIN CONFIGURATION ===
## Default skin: you can change the default skin. Use the internal symbolic
## names
$wgDefaultSkin = "biosterminal";

# Enabled skins.
wfLoadSkin( 'BIOSTerminal' );
# Add Vector as fallback in case of issues
wfLoadSkin( 'Vector' );

## === DEBUG SETTINGS - FOR TROUBLESHOOTING ===
# Add detailed error reporting for database issues
$wgShowDBErrorBacktrace = true;
$wgShowExceptionDetails = true;
$wgShowSQLErrors = true;
$wgDebugDumpSql = true;
$wgDebugLogFile = "/tmp/mediawiki-debug.log";

# End of automatically generated settings.
# Add more configuration options below.
