---
services:
  adnd2e:
    image: mediawiki:latest
    container_name: adnd2e
    hostname: adnd2e
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - MEDIAWIKI_DB_TYPE=mysql
      - MEDIAWIKI_DB_HOST=mariadb
      - MEDIAWIKI_DB_NAME=adnd2e_db
      - MEDIAWIKI_DB_USER=pawneemayor
      - MEDIAWIKI_DB_PASSWORD=password321
      - MEDIAWIKI_SITE_NAME=AD&D 2e Wiki
      - PHP_MEMORY_LIMIT=256M
      - PHP_MAX_EXECUTION_TIME=120
    volumes:
      - /opt/mediawiki/images:/var/www/html/images
      - /opt/mediawiki/cache:/var/www/html/cache
      - /opt/mediawiki/extensions:/var/www/html/extensions
      - /opt/mediawiki/skins:/var/www/html/skins
      - /opt/mediawiki/config:/var/www/html/config
      - /etc/localtime:/etc/localtime:ro
      - /opt/mediawiki/apache-config.conf:/etc/apache2/conf-enabled/servername.conf
      - /opt/mediawiki/php-custom.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - saltbox
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - mariadb
    labels:
      com.github.saltbox.saltbox_managed: true
      traefik.enable: true
      traefik.http.routers.adnd2e-http.entrypoints: web
      traefik.http.routers.adnd2e-http.middlewares: globalHeaders@file,redirect-to-https@docker,robotHeaders@file,cloudflarewarp@docker
      traefik.http.routers.adnd2e-http.rule: Host(`adnd2e.mayorgergich.xyz`)
      traefik.http.routers.adnd2e-http.service: adnd2e
      traefik.http.routers.adnd2e.entrypoints: websecure
      traefik.http.routers.adnd2e.middlewares: globalHeaders@file,secureHeaders@file,robotHeaders@file,cloudflarewarp@docker
      traefik.http.routers.adnd2e.rule: Host(`adnd2e.mayorgergich.xyz`)
      traefik.http.routers.adnd2e.service: adnd2e
      traefik.http.routers.adnd2e.tls.certresolver: cfdns
      traefik.http.routers.adnd2e.tls.options: securetls@file
      traefik.http.services.adnd2e.loadbalancer.server.port: 80

  # Use the existing MariaDB that's already running
  # This is commented out because we're reusing the existing container
  # Uncomment if you want to create a dedicated MariaDB instance for MediaWiki
  #
  # mariadb:
  #   image: mariadb:10.6
  #   container_name: mediawiki-db
  #   restart: unless-stopped
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=rootpassword
  #     - MYSQL_DATABASE=adnd2e_db
  #     - MYSQL_USER=pawneemayor
  #     - MYSQL_PASSWORD=password321
  #     - TZ=UTC
  #   volumes:
  #     - /opt/mediawiki-mariadb:/var/lib/mysql
  #     - /opt/mediawiki/mariadb-custom.cnf:/etc/mysql/conf.d/custom.cnf:ro
  #   networks:
  #     - saltbox
  #   healthcheck:
  #     test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$MYSQL_ROOT_PASSWORD"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3
  #     start_period: 60s
  #   command: mysqld --innodb_buffer_pool_size=2G --max_connections=100 --thread_cache_size=20

networks:
  saltbox:
    external: true
