<?php
# This file was automatically generated by the MediaWiki 1.43.1
# installer and has been optimized for performance.
#
# See includes/MainConfigSchema.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# https://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}

## Basic Wiki Settings
$wgSitename = "ADND2e";
$wgMetaNamespace = "AD&D2e";

## URL Configuration
$wgScriptPath = "";
$wgServer = "https://adnd2e.mayorgergich.xyz";
$wgResourceBasePath = $wgScriptPath;
$wgUsePathInfo = true;

## Logo Configuration
$wgLogos = [
	'1x' => "$wgResourceBasePath//favicon.ico",
	'icon' => "$wgResourceBasePath/images/logo.png",
];

## Email Configuration
$wgEnableEmail = true;
$wgEnableUserEmail = true;
$wgEmergencyContact = "";
$wgPasswordSender = "";
$wgEnotifUserTalk = false;
$wgEnotifWatchlist = false;
$wgEmailAuthentication = true;

## Database Settings
$wgDBtype = "mysql";
$wgDBserver = "mariadb";
$wgDBname = "adnd2e_db";
$wgDBuser = "pawneemayor";
$wgDBpassword = "password321";
$wgDBprefix = "";
$wgDBssl = false;
$wgDBTableOptions = "ENGINE=InnoDB, DEFAULT CHARSET=binary";
$wgDBmysql5 = false;  # Disable for MariaDB 10+
$wgMysqlSlave = false; # Only enable if you have database replicas

# Shared database table
$wgSharedTables[] = "actor";

## Performance Optimization - Cache Settings
$wgMainCacheType = CACHE_ACCEL;
$wgParserCacheType = CACHE_ACCEL;
$wgMessageCacheType = CACHE_ACCEL;
$wgSessionCacheType = CACHE_ACCEL;
$wgMemCachedServers = [];

## Cache Directory Configuration
$wgCacheDirectory = "$IP/cache";
$wgUseFileCache = false;
$wgFileCacheDirectory = "$IP/cache";

## Resource Loader Performance
$wgResourceLoaderMaxage['versioned'] = 60 * 60 * 24 * 30; # 30 days
$wgResourceLoaderMaxage['unversioned'] = 60 * 60 * 24;    # 1 day
$wgEnableSidebarCache = true;
$wgAdaptiveMessageCache = true;

## Upload and Image Settings
$wgEnableUploads = true;
$wgUseImageMagick = true;
$wgImageMagickConvertCommand = "/usr/bin/convert";
$wgMaxShellMemory = 524288; # 512MB for image processing
$wgMaxShellFileSize = 102400; # 100MB max file size
$wgVerifyMimeType = true;
$wgDirectoryMode = 0755; # More secure than 0777

## Integration Settings
$wgUseInstantCommons = false;
$wgPingback = true;

## Localization Settings
$wgLanguageCode = "en";
$wgLocaltimezone = "UTC";

## Security Settings
$wgSecretKey = "2bb341eaf6836414e801e978a37eb6db4ec92b531fec7d7758ee27fe15424f6e";
$wgAuthenticationTokenVersion = "1";
$wgUpgradeKey = "65ad112463df7681";

## Rights and Licensing
$wgRightsPage = "";
$wgRightsUrl = "";
$wgRightsText = "";
$wgRightsIcon = "";

## Diff Tool
$wgDiff3 = "/usr/bin/diff3";

## Skin Configuration
$wgDefaultSkin = "biosterminal";
wfLoadSkin( 'BIOSTerminal' );

## Debug Settings - Comment these out in production
$wgShowExceptionDetails = true;
$wgShowDBErrorBacktrace = true;
$wgShowSQLErrors = true;
$wgDebugLogFile = "$IP/debug.log";

## PHP Settings
ini_set('memory_limit', '512M');
ini_set('max_execution_time', 300);
ini_set('post_max_size', '50M');
ini_set('upload_max_filesize', '50M');
ini_set('max_input_time', 300);

## Parser Performance Settings
$wgTransformsWithCurlyBraceContainmentDisabled = ['nowiki'];
$wgExpensiveParserFunctionLimit = 500;
$wgAllowSlowParserFunctions = true;

## Job Queue Settings
$wgJobRunRate = 0.01;
$wgRunJobsAsync = true;

## API Settings
$wgEnableAPI = true;
$wgEnableWriteAPI = true;
$wgAPIMaxDBRows = 5000;
$wgAPIMaxResultSize = 8388608; # 8MB

## Authentication
$wgPasswordPolicy['policies']['default']['MinimalPasswordLength'] = 8;
$wgPasswordPolicy['policies']['default']['MinimumPasswordLengthToLogin'] = 1;

## External Links
$wgAllowExternalImages = true;
$wgAllowExternalImagesFrom = [];
$wgEnableImageWhitelist = true;

## Optimizations to prevent timeouts
$wgMiserMode = false; # With your resources, this can be false
$wgMaxArticleSize = 10485760; # 10MB max article size
