#!/bin/bash
# Automated MediaWiki Docker Setup Script

# Set working directory
cd /opt/mediawiki

# Backup existing configuration if needed
echo "Creating backups of existing data..."
if [ -d "wiki" ]; then
  mv wiki wiki_backup_$(date +%Y%m%d_%H%M%S)
fi
if [ -f "LocalSettings.php" ]; then
  mv LocalSettings.php LocalSettings.php.backup_$(date +%Y%m%d_%H%M%S)
fi

# Create necessary directories
echo "Creating required directories..."
mkdir -p wiki
mkdir -p images

# Create docker-compose file
echo "Creating docker-compose.yml file..."
cat > docker-compose.yml << 'EOF'
version: "3.8"

services:
  adnd2e:
    image: mediawiki:latest
    container_name: adnd2e
    hostname: adnd2e
    restart: unless-stopped
    environment:
      - MEDIAWIKI_DB_TYPE=mysql
      - MEDIAWIKI_DB_HOST=mariadb
      - MEDIAWIKI_DB_NAME=saltbox
      - MEDIAWIKI_DB_USER=pawneemayor
      - MEDIAWIKI_DB_PASSWORD=password321
      # Auto-installation parameters
      - MEDIAWIKI_SITE_NAME=AD&D 2E Wiki
      - MEDIAWIKI_ADMIN_USER=admin
      - MEDIAWIKI_ADMIN_PASS=password
      - MEDIAWIKI_UPDATE=true
    volumes:
      - /opt/mediawiki/config:/var/www/html/config
      - /opt/mediawiki/images:/var/www/html/images
      - /opt/mediawiki/extensions:/var/www/html/extensions
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - mariadb
    networks:
      - saltbox
    labels:
      com.github.saltbox.saltbox_managed: true
      traefik.enable: true
      traefik.http.routers.adnd2e-http.entrypoints: web
      traefik.http.routers.adnd2e-http.middlewares: globalHeaders@file,redirect-to-https@docker,robotHeaders@file,cloudflarewarp@docker
      traefik.http.routers.adnd2e-http.rule: Host(`adnd2e.mayorgergich.xyz`)
      traefik.http.routers.adnd2e-http.service: adnd2e
      traefik.http.routers.adnd2e.entrypoints: websecure
      traefik.http.routers.adnd2e.middlewares: globalHeaders@file,secureHeaders@file,robotHeaders@file,cloudflarewarp@docker,authelia@file
      traefik.http.routers.adnd2e.rule: Host(`adnd2e.mayorgergich.xyz`)
      traefik.http.routers.adnd2e.service: adnd2e
      traefik.http.routers.adnd2e.tls.certresolver: cfdns
      traefik.http.routers.adnd2e.tls.options: securetls@file
      traefik.http.services.adnd2e.loadbalancer.server.port: 80

  mariadb:
    image: mariadb:10.6
    container_name: adnd2e-db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=saltbox
      - MYSQL_USER=pawneemayor
      - MYSQL_PASSWORD=password321
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - saltbox

networks:
  saltbox:
    external: true

volumes:
  mariadb_data:
  mediawiki_data:
EOF

# Create basic LocalSettings.php template
echo "Creating LocalSettings.php template..."
cat > LocalSettings.php << 'EOF'
<?php
# This file was automatically generated by the MediaWiki installer.
# If you make manual changes, please keep track in case you need to
# recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
    exit;
}

## Database settings
$wgDBtype = "mysql";
$wgDBserver = "mariadb";
$wgDBname = "saltbox";
$wgDBuser = "pawneemayor";
$wgDBpassword = "password321";

## Site settings
$wgSitename = "AD&D 2E Wiki";
$wgMetaNamespace = "AD&D_2E_Wiki";

## Server settings
$wgServer = "https://adnd2e.mayorgergich.xyz";
$wgScriptPath = "";

## File paths and directories
$wgUseImageMagick = true;
$wgImageMagickConvertCommand = "/usr/bin/convert";
$wgEnableUploads = true;
$wgUploadDirectory = "{$IP}/images";
$wgUploadPath = "{$wgScriptPath}/images";

## Default skin
$wgDefaultSkin = "vector";

## Cache settings
$wgMainCacheType = CACHE_NONE;
$wgMemCachedServers = [];

## User rights
$wgGroupPermissions['*']['edit'] = false;

## Admin user
$wgSysopName = "admin";
$wgSysopPassword = "admin_password";

## Shared memory settings
$wgMainCacheType = CACHE_NONE;
$wgMemCachedServers = [];

## Email settings
$wgEnableEmail = false;
$wgEnableUserEmail = false;

## For more information
$wgShowExceptionDetails = true;
$wgShowSQLErrors = true;
$wgDebugDumpSql = true;
$wgShowDBErrorBacktrace = true;

## Extensions
wfLoadExtension( 'WikiEditor' );

# End of automatically generated settings
EOF

# Start containers
echo "Starting containers..."
docker compose down
docker compose up -d

# Wait for services to be ready
echo "Waiting for services to start..."
sleep 30

echo "MediaWiki should now be accessible at https://adnd2e.mayorgergich.xyz"
echo "You can login with username 'admin' and password 'admin_password'"
echo "IMPORTANT: Change the admin password after first login!"

# Instructions for importing custom content
echo ""
echo "To import your custom content:"
echo "1. Go to Special:Import on your wiki"
echo "2. Upload your .mediawiki files"
echo "3. Or use the maintenance/importTextFiles.php script in the container"

echo ""
echo "Setup completed!"
