<?php
# This file was automatically generated by the MediaWiki 1.43.1
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.

# Protect against web entry
if (!defined('MEDIAWIKI')) {
    exit;
}

$wgSitename = 'ADND2e';
$wgMetaNamespace = 'AD&D2e';
$wgScriptPath = '';
$wgServer = 'https://adnd2e.mayorgergich.xyz';
$wgResourceBasePath = $wgScriptPath;

$wgLogos = [
    '1x' => "$wgResourceBasePath/images/logo.png",
    'icon' => "$wgResourceBasePath/images/favicon.ico",
];

# Database settings
$wgDBtype = 'mysql';
$wgDBserver = '172.19.0.11';
$wgDBname = 'adnd2e_db';
$wgDBuser = 'pawneemayor';
$wgDBpassword = 'password321';
$wgDBprefix = '';
$wgDBssl = false;
$wgDBmwschema = null;
$wgDBTableOptions = "ENGINE=InnoDB, DEFAULT CHARSET=utf8mb4, ROW_FORMAT=DYNAMIC";

# Cache settings
$wgMainCacheType = CACHE_NONE;
$wgCacheDirectory = "$IP/cache";

# Default skin 
$wgDefaultSkin = "vector";

# Enabled skins
wfLoadSkin('Vector');
# wfLoadSkin('BIOSTerminal');

# Debug settings
$wgShowExceptionDetails = true;
$wgShowDBErrorBacktrace = true;
$wgShowSQLErrors = true;
