version: "3.8"
services:
  adnd2e:
    image: mediawiki:latest
    container_name: adnd2e
    hostname: adnd2e
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - MEDIAWIKI_DB_TYPE=mysql
      - MEDIAWIKI_DB_HOST=mariadb
      - MEDIAWIKI_DB_NAME=mediawiki_fresh
      - MEDIAWIKI_DB_USER=pawneemayor
      - MEDIAWIKI_DB_PASSWORD=password321
      - MEDIAWIKI_SITE_NAME=AD&D 2E Wiki
    volumes:
      - /opt/mediawiki/images:/var/www/html/images
      - /etc/localtime:/etc/localtime:ro
      - /opt/mediawiki/apache-config.conf:/etc/apache2/conf-enabled/servername.conf
    networks:
      - saltbox
    labels:
      com.github.saltbox.saltbox_managed: true
      traefik.enable: true
      traefik.http.routers.adnd2e-http.entrypoints: web
      traefik.http.routers.adnd2e-http.middlewares: globalHeaders@file,redirect-to-https@docker,robotHeaders@file,cloudflarewarp@docker
      traefik.http.routers.adnd2e-http.rule: Host(`adnd2e.mayorgergich.xyz`)
      traefik.http.routers.adnd2e-http.service: adnd2e
      traefik.http.routers.adnd2e.entrypoints: websecure
      traefik.http.routers.adnd2e.middlewares: globalHeaders@file,secureHeaders@file,robotHeaders@file,cloudflarewarp@docker
      traefik.http.routers.adnd2e.rule: Host(`adnd2e.mayorgergich.xyz`)
      traefik.http.routers.adnd2e.service: adnd2e
      traefik.http.routers.adnd2e.tls.certresolver: cfdns
      traefik.http.routers.adnd2e.tls.options: securetls@file
      traefik.http.services.adnd2e.loadbalancer.server.port: 80

networks:
  saltbox:
    external: true
